Rails.application.routes.draw do
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/signup', to: 'accounts#new'
  post '/signup', to: 'accounts#create'
  get '/config', to: 'accounts#edit'
  patch '/accounts/update', to: 'accounts#update'
  get '/withdraw', to: 'accounts#withdraw'
  delete '/withdraw', to: 'accounts#delete'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/password_resets/new', to: 'password_resets#new'
  post '/password_resets', to: 'password_resets#create'
  get '/password_resets/:reset_token/edit', to: 'password_resets#edit'
end
